spring:
  config:
    import: application-secret.yml
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database: mysql

    generate-ddl: 'true'
    show-sql: 'true'
    hibernate :
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'


log4jdbc:
  auto-load-driver: false
  real-driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:/mapper/**/*Mapper.xml
    type-aliases-package: com.example.PortfolioV1.board.dto
    configuration:
      map-underscore-to-camel-case: true
